name: Feature request
description: Suggest an idea for Numeric Clock
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this feature solve?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature you’d like
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
